name: Continuous Integration Test

on:
  push:
    branches:
    - main
    paths:
    - project/**

jobs:
  continuous_integration:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: main


    # Install python
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    # Show GitHub Workspace
    - name: Print GITHUB_WORKSPACE
      run: echo ${GITHUB_WORKSPACE}

  run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run script file
      run: |
         chmod +x ./public/action/tests.sh
         ./public/action/tests.sh
      shell: bash
        